<h1 style="background-color: #2d90b467; padding: 10px; border-radius: 5px; font-weight: bold; color: #efeacf; text-align: center;">
    Numpy
</h1>

## 🔢 What is NumPy?

**NumPy (Numerical Python)** is a Python library used for **numerical computing and working with arrays**.

### 🔹 Why use NumPy?

NumPy makes it easier and faster to:

* 🔢 Work with numerical data
* 📊 Perform calculations on large datasets
* 🧮 Perform mathematical operations
* 🧱 Create and manipulate arrays
* 📈 Perform basic statistical calculations

### 💡 In Simple Words

> **NumPy = Numerical computing with Python**

NumPy is also an important foundation for libraries such as **Pandas**, **Matplotlib**, and many Machine Learning tools.

---

### 📦 Installing and Importing NumPy

### 🔧 Installing NumPy

If NumPy is not already installed, install it using:

```python
!pip install numpy
```

### 📥 Importing NumPy

The commonly used alias for NumPy is `np`.

```python
import numpy as np
```


> 💡 **Remember:** `import numpy as np` is the standard way to import NumPy.

---

### 🧱 Creating NumPy Arrays

The main data structure in NumPy is the **array**.

We can create an array using `np.array()`.

#### 🔹 1D Array

```python
arr = np.array([10, 20, 30, 40, 50])

print(arr)
```

#### 🔹 2D Array

```python
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr_2d)
```

#### 🔹 Creating an Array from a List

```python
lst = [10, 20, 30]
arr_list = np.array(lst)

print(arr_list)
```

#### 🔹 Useful Array Creation Functions

```python
np.zeros(5)
```

Creates an array filled with zeros.

```python
np.ones(5)
```

Creates an array filled with a number.

```python
np.full((2, 2), 7)
```

Creates an array filled with ones.

```python
np.arange(1, 10)
```

Creates values from `1` to `9`.

```python
np.linspace(0, 1, 5)
```

Creates 5 evenly spaced values between `0` and `1`.

Creates an Identity Matrix.

```python
np.eye(3)   #3*3 Identity Matrix
```

---

### 📐 Array Dimensions, Shape & Size

NumPy provides useful attributes to understand the structure of an array.

```python
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.dtype)
```

#### 🔹 Important Attributes

| Attribute | Meaning                  |
| --------- | ------------------------ |
| `.ndim`   | Number of dimensions     |
| `.shape`  | Rows and Columns  |
| `.size`   | Total number of elements |
| `.dtype`  | Data type of elements    |

---


### 🎯 Accessing Array Values

We can access individual values from a NumPy array using **indexing**.

#### 🔹 1D Array

```python
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[2])
print(arr[-1])
```

#### 🔹 2D Array

```python
arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print(arr[0, 1])
print(arr[1, 2])
```

> 💡 In a 2D array, use `arr[row, column]` to access a specific value.

---

### 🎯 Indexing & Slicing

NumPy arrays use **zero-based indexing**, just like Python lists.

#### 🔹 Indexing

```python
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])    # First element
print(arr[2])    # Third element
print(arr[-1])   # Last element
```

#### 🔹 Slicing

```python
print(arr[1:4])
print(arr[:3])
print(arr[2:])
```

#### 🔹 2D Array Indexing

```python
arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(arr_2d[0, 1])
print(arr_2d[1, 2])
```

> 💡 **Remember:** `arr[row, column]` is used to access an element in a 2D array.

---

### ➕ Array Operations

NumPy allows us to perform mathematical operations directly on arrays.

```python
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)
print(a - b)
print(a * b)
print(a / b)
```

#### 🔹 Operations with a Single Number

```python
print(a + 5)
print(a * 2)
print(a / 10)
```

NumPy performs the operation on **every element** of the array without using loops. This is known as vectorization.

> 💡 This makes numerical calculations much easier than using traditional Python loops.

---

### ✏️ Replacing Values

We can replace values in a NumPy array using **indexing**.

```python
arr = np.array([10, 20, 30, 40, 50])

arr[2] = 100

print(arr)
```

Output:

```text
[ 10  20 100  40  50]
```

#### 🔹 Replacing Multiple Values with a Condition

We can use a condition to replace multiple values.

```python
arr = np.array([10, 25, 35, 45, 55])

arr[arr > 40] = 0

print(arr)
```

Output:

```text
[10 25 35  0  0]
```

Here, all values greater than `40` are replaced with `0`.

> 💡 **Condition + assignment** is a powerful way to modify multiple NumPy values.

---

### 🧮 Mathematical Functions

NumPy provides many built-in mathematical functions.

```python
arr = np.array([1, 4, 9, 16])

print(np.sqrt(arr))
print(np.square(arr))
print(np.sum(arr))
print(np.mean(arr))
```

#### 🔹 Common Functions

| Function      | Purpose        |
| ------------- | -------------- |
| `np.sqrt()`   | Square root    |
| `np.square()` | Square         |
| `np.sum()`    | Sum of values  |
| `np.mean()`   | Average        |
| `np.min()`    | Minimum        |
| `np.max()`    | Maximum        |
| `np.abs()`    | Absolute value |

> 💡 NumPy functions allow us to perform calculations efficiently on entire arrays.

---

### 🔄 Reshaping Arrays

The `reshape()` method changes the **structure or shape** of an array without changing its values.

#### 🔹 Example

```python
arr = np.arange(1, 7)

print(arr)
```

Output:

```text
[1 2 3 4 5 6]
```

Now reshape it into 2 rows and 3 columns:

```python
new_arr = arr.reshape(2, 3)

print(new_arr)
```

Output:

```text
[[1 2 3]
 [4 5 6]]
```

Now lets convert it back to a single 1d Array:

```python
new_arr2 = arr.flatten()

print(new_arr2)
```

Output:

```text
[1 2 3 4 5 6]
```

#### 🧠 Remember

```text
1 2 3 4 5 6
      ↓
   reshape
      ↓
1 2 3
4 5 6
      ↓
   flatten
      ↓
1 2 3 4 5 6
```

> 💡 The total number of elements must remain the same when reshaping.

---

### 📊 Basic Statistics with NumPy

NumPy can be used to calculate common statistical values.

```python
marks = np.array([70, 80, 90, 60, 85])

print("Mean:", np.mean(marks))
print("Median:", np.median(marks))
print("Standard Deviation:", np.std(marks))
print("Variance:", np.var(marks))
print("Minimum:", np.min(marks))
print("Maximum:", np.max(marks))
```

#### 🔹 Common Statistical Functions

| Function      | Purpose            |
| ------------- | ------------------ |
| `np.mean()`   | Average            |
| `np.median()` | Middle value       |
| `np.std()`    | Standard deviation |
| `np.var()`    | Variance           |
| `np.min()`    | Minimum            |
| `np.max()`    | Maximum            |

> 💡 These functions are useful when exploring and understanding numerical datasets.

---

### 🔍 Filtering Data

NumPy allows us to filter arrays using **conditions**.

```python
arr = np.array([10, 20, 30, 40, 50])

filtered = arr[arr > 25]

print(filtered)
```

Output:

```text
[30 40 50]
```

#### 🔹 Multiple Conditions

```python
arr = np.array([10, 20, 30, 40, 50])

filtered = arr[(arr > 20) & (arr < 50)]

print(filtered)
```

Output:

```text
[30 40]
```

#### 🧠 Remember

```text
arr[condition]
      ↓
Returns only values where the condition is True
```

---

### 🔗 Combining Arrays

NumPy provides functions to combine multiple arrays.

#### 🔹 `np.concatenate()`

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

result = np.concatenate((a, b))

print(result)
```

Output:

```text
[1 2 3 4 5 6]
```

#### 🔹 Combining 2D Arrays

```python
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.concatenate((a, b))

print(result)
```

Output:

```text
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
```

#### 🔹 Stack Arrays

```python
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Vertical Stack : ", np.vstack((a, b)))
print()
print("Horizontal Stack : ",np.hstack((a, b)))
```

Output:

```text
[[1 2 3]
 [4 5 6]]

[1 2 3 4 5 6]
```

* `vstack()` → combines vertically
* `hstack()` → combines horizontally

> 💡 Combining arrays is useful when working with data from different sources.

---
---